export const GET_COURSES_ACTION = 'GET COURSES ACTION';
export const WAITING_FOR_GET_COURSES = 'WAITING FOR GET COURSES';
export const GETTING_COURSES_ERROR = 'GETTING COURSES ERROR';
export const GET_TASKS = 'GET TASKS';
