export const MOVE_TASK_TO_DESTINATION_COLUMN = 'MOVE TASK TO ANOTHER COLUMN';
export const MOVE_TASK_FROM_ORIGINAL_COLUMN = 'MOVE TASK FROM ORIGINAL COLUMN';
export const GET_TASKS = 'GET TASKS';
export const GET_TASK = 'GET TASK';
